### ISSUE TITLE
Does not compile with rocket 0.5.0 (not Rc3)

### ISSUE THREAD

**Issue by robertsarkozi** [tvallotton/rocket_auth#69]
It does not compile when you create a project with only rocket 0.5.0 and rocket_auth 0.4.0
Cargo.toml:

```toml
[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"
rocket_auth = "0.4.0"
```

[build_errors.txt](https://github.com/tvallotton/rocket_auth/files/14538082/build_errors.txt)
